/* =========================================================================
   data.js: datasets as JS objects (spec §6)
   -------------------------------------------------------------------------
   The engine reads a flat cell map ({ A1: "OrderID", F2: 3, … }). Humans
   (and the §6 generator) think in tables. toCells() turns a list of
   positioned tables into one cell map, so a sheet can hold an orders table
   in A:F and a lookup table in H:J side by side, exactly like v1.

   AEGEAN is the course dataset (spec §6), generated by
   content/_generators/aegean.mjs. One sheet, four tables side by side:

     A:H  Orders    OrderID · Date · ProductID · Region · Rep · Channel · Quantity · Discount
     J:N  Products  ProductID · ProductName · Category · UnitCost · ListPrice
     P:T  Reps      RepID · RepName · Region · HireDate · Target
     V:X  Tiers     MinQty · Band · Discount   (sorted, for approximate match)

   Dates are Excel date serials (numbers), exactly as Excel stores them, so
   COUNT sees them and they sort correctly. `formats` tells the sheet to SHOW
   them as dates, and discounts as percentages. The engine only ever sees the
   raw numbers.
   AEGEAN_MESSY is the same order log with seeded defects (Level 3 cleaning);
   `defects` documents each one so the grader can verify fixes.

   V1_SAMPLE is the v1 app's 24-order dataset. It's kept for the engine and
   UI tests and the console demo page; course content uses AEGEAN.
   ========================================================================= */
import AEGEAN_RAW from "./data/aegean.generated.js";

/** Column letters ↔ 1-based index. */
export function colToIndex(letters) { let n = 0; for (const ch of letters) n = n * 26 + (ch.charCodeAt(0) - 64); return n; }
export function indexToCol(n) { let s = ""; while (n > 0) { s = String.fromCharCode(65 + ((n - 1) % 26)) + s; n = Math.floor((n - 1) / 26); } return s; }

/**
 * Build a cell map from positioned tables.
 * @param {{origin: string, header?: string[], rows: any[][]}[]} tables
 *   origin: top-left cell of the table (the header row if there is one), e.g. "H1".
 * @returns {Object<string, string|number|boolean>} frozen cell map. Empty cells are simply absent.
 */
export function toCells(tables) {
  const cells = {};
  for (const t of tables) {
    const m = /^([A-Z]+)(\d+)$/.exec(t.origin);
    if (!m) throw new Error(`Bad table origin "${t.origin}"`);
    const c0 = colToIndex(m[1]); let r = Number(m[2]);
    const put = (row, rr) => row.forEach((v, i) => {
      if (v === null || v === undefined || v === "") return;
      const key = indexToCol(c0 + i) + rr;
      if (key in cells) throw new Error(`Tables overlap at ${key}`);
      cells[key] = v;
    });
    if (t.header) put(t.header, r++);
    t.rows.forEach(row => put(row, r++));
  }
  return Object.freeze(cells);
}

/* ---------- v1 sample (24 orders + 8 products) ---------- */
const V1_ORDERS = [["O1000","2024-01-20","P006","West","A. Ioannou",3],["O1001","2024-02-16","P002","North","E. Makris",7],["O1002","2024-01-12","P001","West","D. Georgiou",3],["O1003","2024-01-12","P004","West","A. Ioannou",19],["O1004","2024-01-29","P002","North","E. Makris",19],["O1005","2024-03-04","P007","East","B. Petrou",12],["O1006","2024-02-19","P001","South","C. Nikolaou",8],["O1007","2024-01-08","P003","North","D. Georgiou",5],["O1008","2024-03-22","P005","East","A. Ioannou",14],["O1009","2024-02-02","P002","South","E. Makris",2],["O1010","2024-01-25","P008","West","B. Petrou",16],["O1011","2024-03-11","P004","North","C. Nikolaou",9],["O1012","2024-02-27","P001","East","D. Georgiou",6],["O1013","2024-01-17","P006","South","A. Ioannou",11],["O1014","2024-03-30","P002","West","E. Makris",4],["O1015","2024-02-13","P007","North","B. Petrou",18],["O1016","2024-01-05","P003","East","C. Nikolaou",13],["O1017","2024-03-08","P005","South","D. Georgiou",7],["O1018","2024-02-21","P001","North","A. Ioannou",10],["O1019","2024-01-30","P004","East","E. Makris",15],["O1020","2024-03-15","P002","West","B. Petrou",5],["O1021","2024-02-08","P008","South","C. Nikolaou",20],["O1022","2024-01-19","P006","North","D. Georgiou",6],["O1023","2024-03-26","P007","East","A. Ioannou",9]];
const V1_PRODUCTS = [["P001","Laptop",720],["P002","Monitor",190],["P003","Keyboard",45],["P004","Mouse",25],["P005","Docking Station",130],["P006","Webcam",60],["P007","Headset",85],["P008","USB Hub",35]];

export const V1_SAMPLE = Object.freeze({
  id: "v1-sample",
  label: "v1 sample: 24 orders (A:F) + product table (H:J)",
  range: "A1:J25",
  headerRows: 1,
  cells: toCells([
    { origin: "A1", header: ["OrderID", "Date", "ProductID", "Region", "Rep", "Quantity"], rows: V1_ORDERS },
    { origin: "H1", header: ["ProductID", "ProductName", "UnitPrice"], rows: V1_PRODUCTS },
  ]),
});

/* ---------- Aegean Supplies (spec §6) ---------- */
export const AEGEAN_TABLES = Object.freeze({
  orders: { origin: "A1", header: ["OrderID", "Date", "ProductID", "Region", "Rep", "Channel", "Quantity", "Discount"], rows: AEGEAN_RAW.orders },
  products: { origin: "J1", header: ["ProductID", "ProductName", "Category", "UnitCost", "ListPrice"], rows: AEGEAN_RAW.products },
  reps: { origin: "P1", header: ["RepID", "RepName", "Region", "HireDate", "Target"], rows: AEGEAN_RAW.reps },
  tiers: { origin: "V1", header: ["MinQty", "Band", "Discount"], rows: AEGEAN_RAW.tiers },
});
const lastOrderRow = AEGEAN_RAW.orders.length + 1;
export const AEGEAN = Object.freeze({
  id: "aegean",
  label: "Aegean Supplies 2025: Orders (A:H), Products (J:N), Reps (P:T), Tiers (V:X)",
  range: `A1:X${lastOrderRow}`,
  headerRows: 1,
  formats: Object.freeze({ B: "date", H: "percent", S: "date", X: "percent" }),
  lastOrderRow,
  cells: toCells(Object.values(AEGEAN_TABLES)),
  raw: AEGEAN_RAW,
});
// The messy export sits in A:H; the (clean) reference tables stay where they are in J:X,
// so a lookup you learned in Level 2 works unchanged while you clean.
const REF_TABLES = [AEGEAN_TABLES.products, AEGEAN_TABLES.reps, AEGEAN_TABLES.tiers];
export const AEGEAN_MESSY = Object.freeze({
  id: "aegean-messy",
  label: "Aegean Supplies: raw order export (messy) in A:H, reference tables in J:X",
  range: `A1:X${AEGEAN_RAW.messy.orders.length + 1}`,
  headerRows: 1,
  formats: AEGEAN.formats,
  cells: toCells([{ ...AEGEAN_TABLES.orders, rows: AEGEAN_RAW.messy.orders }, ...REF_TABLES]),
  orders: Object.freeze({ header: AEGEAN_TABLES.orders.header, rows: AEGEAN_RAW.messy.orders }),
  refTables: REF_TABLES,
  defects: AEGEAN_RAW.messy.defects,
  raw: AEGEAN_RAW,   // raw.orders is the clean log the cleaning audit compares against
});

/* ---------- display formats (shared by the sheet and the console) ---------- */
/** Excel date serial → "YYYY-MM-DD". */
export function serialToISO(n) {
  const d = new Date(Date.UTC(1899, 11, 30) + Math.round(n) * 86400000);
  return d.toISOString().slice(0, 10);
}
/** Show a raw value the way its column is formatted ("date", "percent"), like Excel's number formats. */
export function formatAs(v, format) {
  if (typeof v !== "number" || !format) return null;
  if (format === "date") return serialToISO(v);
  if (format === "percent") return `${Math.round(v * 10000) / 100}%`;
  return null;
}
/** The format of a cell, from its column letter. */
export function formatOf(dataset, key) {
  const m = /^([A-Z]+)\d+$/.exec(key || ""); return m ? dataset?.formats?.[m[1]] || null : null;
}

/** Registry so content JSON can refer to a dataset by id. */
export const DATASETS = Object.freeze({ [V1_SAMPLE.id]: V1_SAMPLE, [AEGEAN.id]: AEGEAN, [AEGEAN_MESSY.id]: AEGEAN_MESSY });
